import axios from 'axios';

const wrapPrompt = (body) => `You are a professional resume expert helping someone craft their resume. Write naturally and conversationally, as if you're a human career coach. Avoid repetitive phrases, generic buzzwords, and overly formal language. Be specific and authentic.\n\n${body}\n\nIMPORTANT: Write in a natural, human style. Vary your sentence structure and word choice. Avoid using the same phrases repeatedly. Make it sound like it was written by the person themselves, not generated by AI.`;

// Smart fallback generator that creates professional content without external APIs
const generateFallback = (prompt) => {
    const lower = prompt.toLowerCase();

    // Extract key information from prompt
    const nameMatch = prompt.match(/for ([A-Z][a-z]+ [A-Z][a-z]+)|named ([A-Z][a-z]+ [A-Z][a-z]+)/);
    const name = nameMatch ? (nameMatch[1] || nameMatch[2]) : 'the candidate';

    // Extract skills
    const skillsMatch = prompt.match(/skills?:\s*([^.\n]+)/i);
    const skills = skillsMatch ? skillsMatch[1].trim() : '';

    // Extract experience/roles
    const experienceMatch = prompt.match(/experience:\s*([^.\n]+)|roles?:\s*([^.\n]+)|position:\s*([^\n]+)|role:\s*([^\n]+)/i);
    const experience = experienceMatch ? (experienceMatch[1] || experienceMatch[2] || experienceMatch[3] || experienceMatch[4])?.trim() : '';

    // Extract company
    const companyMatch = prompt.match(/company:\s*([^\n(]+)/i);
    const company = companyMatch ? companyMatch[1].trim() : '';

    // Extract project title
    const projectMatch = prompt.match(/project (?:title|called):\s*"([^"]+)"|project:\s*([^\n]+)/i);
    const projectTitle = projectMatch ? (projectMatch[1] || projectMatch[2])?.trim() : '';

    // Extract tech stack
    const techMatch = prompt.match(/(?:built with|using|tech stack|technologies?):\s*([^.\n]+)/i);
    const techStack = techMatch ? techMatch[1].trim() : '';

    // Generate Skills List
    if (lower.includes('list') && lower.includes('skill')) {
        const baseSkills = [];
        const roles = experience.toLowerCase();

        // Add role-specific skills
        if (roles.includes('full stack') || roles.includes('fullstack')) {
            baseSkills.push('React', 'Node.js', 'Express.js', 'MongoDB', 'PostgreSQL', 'TypeScript', 'REST API', 'Git', 'Docker', 'AWS', 'Redux', 'Tailwind CSS');
        } else if (roles.includes('frontend') || roles.includes('react')) {
            baseSkills.push('React', 'JavaScript', 'TypeScript', 'HTML5', 'CSS3', 'Tailwind CSS', 'Redux', 'Next.js', 'Webpack', 'Git', 'Responsive Design', 'RESTful APIs');
        } else if (roles.includes('backend') || roles.includes('node')) {
            baseSkills.push('Node.js', 'Express.js', 'MongoDB', 'PostgreSQL', 'REST API', 'GraphQL', 'TypeScript', 'Docker', 'AWS', 'Redis', 'Git', 'Microservices');
        } else if (roles.includes('python') || roles.includes('data')) {
            baseSkills.push('Python', 'Django', 'Flask', 'pandas', 'NumPy', 'Machine Learning', 'SQL', 'PostgreSQL', 'Git', 'Docker', 'REST API', 'Data Analysis');
        } else if (roles.includes('java') || roles.includes('spring')) {
            baseSkills.push('Java', 'Spring Boot', 'Hibernate', 'MySQL', 'REST API', 'Microservices', 'Maven', 'Git', 'Docker', 'Kubernetes', 'JUnit', 'AWS');
        } else {
            // Generic developer skills
            baseSkills.push('JavaScript', 'Python', 'React', 'Node.js', 'SQL', 'Git', 'REST API', 'Docker', 'AWS', 'Agile', 'Problem Solving', 'Team Collaboration');
        }

        return baseSkills.join(', ');
    }

    // Generate Professional Summary
    if (lower.includes('summary') || lower.includes('professional')) {
        const experienceYears = Math.floor(Math.random() * 3) + 2; // 2-4 years
        const skillsList = skills || 'modern web technologies';
        const roleContext = experience || 'software development';

        // Multiple natural-sounding templates
        const templates = [
            `${roleContext.charAt(0).toUpperCase() + roleContext.slice(1)} with ${experienceYears}+ years specializing in ${skillsList}. Known for building reliable, user-focused applications that scale. Enjoy tackling complex problems and working closely with teams to ship quality software. Always looking to learn new technologies and improve existing systems.`,

            `${experienceYears}+ years of hands-on experience in ${roleContext}, working extensively with ${skillsList}. Track record of delivering high-impact features and optimizing application performance. Thrive in fast-paced environments where collaboration and code quality matter. Passionate about creating solutions that make a real difference for users.`,

            `Experienced ${roleContext} professional (${experienceYears}+ years) with deep expertise in ${skillsList}. Specialize in building scalable applications and solving challenging technical problems. Value clean code, thorough testing, and clear communication. Committed to continuous learning and staying ahead of industry trends.`,

            `${experienceYears} years of experience developing and deploying applications using ${skillsList}. Strong focus on ${roleContext} with proven ability to deliver results in collaborative team settings. Enjoy mentoring others and contributing to a positive engineering culture. Always seeking opportunities to grow and take on new challenges.`
        ];

        return templates[Math.floor(Math.random() * templates.length)];
    }

    // Generate Experience Description (bullet points)
    if ((lower.includes('job description') || lower.includes('position')) && company) {
        const role = experience || 'Software Engineer';

        // Multiple varied bullet point sets for natural variety
        const bulletSets = [
            [
                `• Designed and built core features for web applications used by 50K+ customers daily`,
                `• Worked with APIs and databases to create seamless data flows, cutting load times by 40%`,
                `• Partnered with designers and product managers to ship 12+ major features on schedule`,
                `• Helped junior team members grow through code reviews and technical guidance`
            ],
            [
                `• Built scalable backend services that handle millions of requests per day`,
                `• Improved system performance by refactoring legacy code and optimizing database queries`,
                `• Collaborated across teams to launch features that directly increased user engagement`,
                `• Contributed to engineering culture through documentation and knowledge sharing`
            ],
            [
                `• Developed and maintained high-traffic web applications serving a large user base`,
                `• Implemented automated testing and CI/CD pipelines, reducing deployment time significantly`,
                `• Led technical discussions and architecture decisions for new feature development`,
                `• Mentored new engineers and conducted technical interviews to grow the team`
            ],
            [
                `• Created responsive, accessible user interfaces that improved customer satisfaction`,
                `• Integrated third-party services and APIs to extend platform capabilities`,
                `• Optimized application performance through profiling and targeted improvements`,
                `• Participated in agile ceremonies and contributed to sprint planning and retrospectives`
            ]
        ];

        return bulletSets[Math.floor(Math.random() * bulletSets.length)].join('\n');
    }

    // Generate Project Description (bullet points)
    if (lower.includes('project') && projectTitle) {
        const tech = techStack || 'modern web technologies';

        // Multiple varied project description sets
        const projectSets = [
            [
                `• Built full-stack application using ${tech} with features including user auth and data management`,
                `• Focused on responsive design and smooth user experience across all devices`,
                `• Achieved strong performance scores through code optimization and lazy loading`,
                `• Deployed to production with automated testing and continuous integration`
            ],
            [
                `• Created a ${tech}-based application handling real-time data and user interactions`,
                `• Implemented secure authentication and role-based access control`,
                `• Optimized database queries and caching strategies for faster response times`,
                `• Set up monitoring and error tracking to maintain reliability in production`
            ],
            [
                `• Developed interactive web app with ${tech} featuring intuitive UI and smooth navigation`,
                `• Integrated external APIs and services to enhance functionality`,
                `• Wrote comprehensive tests to ensure code quality and prevent regressions`,
                `• Containerized application using Docker for consistent deployment across environments`
            ],
            [
                `• Designed and implemented ${tech} application with modern architecture patterns`,
                `• Built RESTful API backend with proper validation and error handling`,
                `• Created responsive frontend that works seamlessly on mobile and desktop`,
                `• Implemented analytics and logging to track usage and identify improvements`
            ]
        ];

        return projectSets[Math.floor(Math.random() * projectSets.length)].join('\n');
    }

    // Generate Cover Letter
    if (lower.includes('cover letter')) {
        return `Dear Hiring Manager,

I am writing to express my strong interest in joining your team. With proven expertise in ${skills || 'software development'}, I am confident in my ability to contribute effectively to your organization.

Throughout my career, I have successfully delivered projects that demonstrate both technical excellence and strong collaboration skills. I am particularly drawn to opportunities where I can apply my knowledge to solve challenging problems and create meaningful impact.

I am excited about the possibility of bringing my skills and enthusiasm to your team and would welcome the opportunity to discuss how I can contribute to your organization's success.

Thank you for considering my application.

Sincerely,
${name}`;
    }

    // Generic professional response
    return `Professional with expertise in ${skills || 'technology'}, committed to delivering high-quality results and continuous learning. Strong technical foundation combined with excellent communication and teamwork abilities.`;
};

export const generateAIContent = async (prompt, maxTokens = 256) => {
    try {
        const apiUrl = process.env.HUGGINGFACE_API_URL?.trim();
        const apiKey = process.env.HUGGINGFACE_API_KEY?.trim();

        // Try Hugging Face if credentials are available
        if (apiUrl && apiKey) {
            try {
                console.log(`🚀 Calling Hugging Face API: ${apiUrl}`);
                const response = await axios.post(
                    apiUrl,
                    {
                        inputs: wrapPrompt(prompt),
                        parameters: {
                            max_new_tokens: maxTokens,
                            temperature: 0.7,
                            return_full_text: false
                        }
                    },
                    {
                        headers: {
                            Authorization: `Bearer ${apiKey}`,
                            'Content-Type': 'application/json'
                        },
                        timeout: 30000
                    }
                );

                const data = response.data;
                console.log('✅ Hugging Face response received');

                let output;
                if (Array.isArray(data)) {
                    output = data[0]?.generated_text || data[0]?.text;
                } else {
                    output = data.generated_text || data.text || data[0]?.generated_text;
                }

                if (output && output.trim()) {
                    return output.trim();
                }
            } catch (error) {
                if (error.response) {
                    console.error('❌ Hugging Face API error:', error.response.status, error.response.data);
                } else {
                    console.error('❌ Hugging Face request failed:', error.message);
                }
            }
        } else {
            console.log('💡 No Hugging Face credentials - using built-in generator');
        }

        // Use smart fallback
        console.log('💡 Using built-in content generator');
        const fallbackResult = generateFallback(prompt);
        
        if (!fallbackResult || fallbackResult.trim() === '') {
            throw new Error('Failed to generate content');
        }
        
        return fallbackResult;
    } catch (error) {
        console.error('❌ Error in generateAIContent:', error);
        // Return a basic fallback message instead of throwing
        return 'Professional with expertise in software development, committed to delivering high-quality results and continuous learning. Strong technical foundation combined with excellent communication and teamwork abilities.';
    }
};
